version: "3"

services:
  petoshield_db:
    image: postgres:latest
    container_name: petoshield_db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    restart: always
    volumes:
      - petoshield_data:/var/lib/postgresql/data/

  petoshield_api:
    build:
      context: ./petoshield_api
      dockerfile: Dockerfile
    command: >
      sh -c "python -m manage migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    image: petoshield:latest
    container_name: petoshield-api
    depends_on:
      - petoshield_db
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_DEBUG: $DJANGO_DEBUG
      DATABASE_ENGINE: $DATABASE_ENGINE
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      CSRF_TRUSTED_ORIGINS: $CSRF_TRUSTED_ORIGINS
      TOKEN_EXPIRE: $TOKEN_EXPIRE
      REFRESH_TOKEN_EXPIRE: $REFRESH_TOKEN_EXPIRE
      CORS_ALLOWED_ORIGINS: $CORS_ALLOWED_ORIGINS
      EMAIL_HOST_USER: $EMAIL_HOST_USER
      EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
      POLICY_BASE_PRICE: $POLICY_BASE_PRICE
    restart: on-failure
    ports:
      - "9044:8000"
    volumes:
      - /var/www/petoshield-data/media:/media

volumes:
  petoshield_data:

