version: "3"

services:
  petoshield_db:
    image: postgres:latest
    container_name: petoshield_db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    restart: always
    volumes:
      - petoshield_database:/var/lib/postgresql/data/

  petoshield_api:
    build:
      context: ./petoshield_api
      dockerfile: Dockerfile
    command: >
      sh -c "python -m manage migrate && python -m manage collectstatic && 
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    image: petoshield:latest
    container_name: petoshield-api
    depends_on:
      - petoshield_db
    restart: on-failure
    ports:
      - "9044:8000"
    volumes:
      - /var/www/petoshield-data/media:/api/media

#  prometheus:
#    image: prom/prometheus:latest
##    ports:
##      - "9090:9090"
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--web.enable-lifecycle'
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
#    network_mode: host
#
#
#  grafana:
#    image: grafana/grafana:latest
##    ports:
##      - "3001:3000"
#    environment:
#      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
#    volumes:
#      - grafana_data:/var/lib/grafana
#    depends_on:
#      - prometheus
#    network_mode: host

volumes:
  petoshield_database:
#  grafana_data:
#  prometheus_data:

