version: "3"

services:
  petoshield_db:
    image: postgres:latest
    container_name: petoshield_db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    restart: always
    volumes:
      - petoshield_data:/var/lib/postgresql/data/

  petoshield_api:
    build:
      context: ./petoshield_api
      dockerfile: Dockerfile
    command: >
      sh -c "python -m manage migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    image: petoshield:latest
    container_name: petoshield-api
    depends_on:
      - petoshield_db
    restart: on-failure
    env_file:
      - .env
    ports:
      - "9044:8000"
    volumes:
      - /var/www/petoshield-data/media:/api/media

volumes:
  petoshield_data:

