global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:

scrape_configs:
  - job_name: "django"
    scheme: https
    static_configs:
      - targets: ["api.petoshield.com"]
