global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:

scrape_configs:
  - job_name: "django"
#    metrics_path: '/metrics'
    static_configs:
      - targets: ["127.0.0.1:8000"]
