# Generated by Django 4.2.6 on 2023-11-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_image_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailverificationtokens',
            name='email_confirmed',
        ),
    ]
