# Generated by Django 4.2.6 on 2023-11-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_mailverificationtokens_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailverificationtokens',
            name='redirect_link',
            field=models.URLField(default='http://example.com'),
        ),
    ]
