# Generated by Django 4.2.6 on 2023-11-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_mailverificationtokens_redirect_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailverificationtokens',
            name='redirect_link',
        ),
    ]
