# Generated by Django 4.2.6 on 2023-10-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incominginvoice',
            name='insurance_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_invoice', to='policy.insurancecase'),
        ),
    ]
