# Generated by Django 4.2.6 on 2023-11-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
        ),
    ]
