# Generated by Django 4.2.6 on 2023-10-29 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_breed_age_max_alter_breed_age_min'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy', '0003_alter_incominginvoice_insurance_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy', to='pet.pet'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
