# Generated by Django 4.2.6 on 2023-10-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_rename_date_incominginvoice_date_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incominginvoice',
            old_name='date_test',
            new_name='date',
        ),
    ]
