# Generated by Django 4.2.6 on 2023-10-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_rename_date_test_incominginvoice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incominginvoice',
            old_name='date',
            new_name='invoice_date',
        ),
    ]
