# Generated by Django 4.2.6 on 2023-10-24 12:31

import apps.pet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(null=True)),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('risk_level', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5)),
                ('species', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('species', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=3)),
                ('breed', models.ForeignKey(on_delete=models.SET(apps.pet.models.get_default_breed), related_name='pets', to='pet.breed')),
            ],
        ),
    ]
