# Generated by Django 4.2.6 on 2023-11-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy', '0003_policy_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=250)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='policy.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
