# Generated by Django 4.2.6 on 2023-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesession',
            name='session_id',
            field=models.TextField(),
        ),
    ]
