# Generated by Django 4.2.6 on 2023-11-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_policy_price'),
        ('payment', '0002_alter_stripesession_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='policy.policy')),
                ('stripe_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='payment.stripecustomer')),
            ],
        ),
    ]
