# Generated by Django 4.2.6 on 2023-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(max_length=125)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_message', models.TextField(max_length=1000)),
                ('is_client', models.BooleanField(default=False)),
                ('company_reply', models.TextField(blank=True, max_length=1000, null=True)),
                ('ticket_status', models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('closed', 'Closed')], default='new')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
