# Generated by Django 4.2.6 on 2023-11-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'tickets'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='company_reply',
        ),
    ]
