# Generated by Django 4.2.6 on 2023-11-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options_remove_ticket_company_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_client',
        ),
    ]
